<?php
/**
 * Created by PhpStorm.
 * User: wang
 * Date: 2018/4/19
 * Time: 下午3:53
 */

namespace Zoran\Xmoov\Servers;


class ImageServer extends StreamServer
{
    public function init()
    {
        if ($this->request->get('file')) {
            return [
                'file' => $this->request->get('file'),
                'file_path' => $this->config['file_path'] . '/images/',
                'force_download' => 0,
                'burst_size' => 0,
                'throttle' => 0,
                'mime_types' => [
                    'jpe' => 'image/jpeg',
                    'jpeg' => 'image/jpeg',
                    'jpg' => 'image/jpeg',
                    'png'  => 'image/png',
                    'svg' => 'image/svg+xml',
                    'tif' => 'image/tiff',
                    'tiff' => 'image/tiff',
                    'gif' => 'image/gif'
                ]
            ];
        }
        return parent::init(); // TODO: Change the autogenerated stub
    }
}