<?php
/**
 * Created by PhpStorm.
 * User: wang
 * Date: 2018/4/19
 * Time: 下午3:53
 */

namespace Zoran\Xmoov\Servers;


class PlayerServer extends StreamServer
{
    public function init()
    {
        $file = $this->request->get('file');
        if ($file) {
            $file = rtrim($file, strstr($file, '.'));
            return [

                'file' => 'player.swf',
                'file_name' => $file . 'player.swf',
                'file_path' => $this->config['file_path'] . '/players/'.$file.'/',
                'force_download' => 0,
                'burst_size' => 0,
                'throttle' => 0,
                'mime_types' => [
                    'swf' => 'application/x-shockwave-flash'
                ]
            ];
        }
        return parent::init(); // TODO: Change the autogenerated stub
    }
}