<?php
/**
 * Created by PhpStorm.
 * User: wang
 * Date: 2018/4/19
 * Time: 下午4:09
 */

namespace Zoran\Xmoov\Servers;


use Zoran\Xmoov\Stream\XmoovStreamToken;

class PrivateDownloadServer extends DownloadServer
{
    /**
     * @var XmoovStreamToken
     * */
    protected $token = null;

    public function setToken(XmoovStreamToken $token) {
        $this->token = $token;
    }

    public function init()
    {
        if($this->request->get('media') !== 'download'){
            return false;
        }

        if(!$this->token->isValid($this->request->get('file'), $this->request->get('key'))){
            return false;
        }
        return parent::init(); // TODO: Change the autogenerated stub
    }
}